apiVersion: 'v2'
name: 'sonarr'
description: 'Chart for Sonarr'
type: 'application'
version: 0.19.0
appVersion: '4.0.1'
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/sonarr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.2.0
    repository: "file://../.."
