apiVersion: 'v2'
name: 'sonarr'
description: 'Television series manager for Usenet and BitTorrent users'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/sonarr'
keywords:
  - 'tv'
  - 'television'
  - 'series'
  - 'torrent'
  - 'bittorrent'
  - 'usenet'
  - 'manager'
  - 'sonarr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.5.1
appVersion: '4.0.3'
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/sonarr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.5.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/Sonarr/Sonarr'
  - 'https://github.com/linuxserver/docker-sonarr'
  - 'https://ghcr.io/onedr0p/exportarr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/sonarr'
