apiVersion: 'v2'
name: 'sabnzbd'
description: 'SABnzbd is a program to download binary files from Usenet servers'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/sabnzbd'
keywords:
  - 'usenet'
  - 'newsreader'
  - 'sabnzbd'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.6.4
appVersion: 4.5.2
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/sabnzbd/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.9.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/sabnzbd/sabnzbd'
  - 'https://hub.docker.com/r/linuxserver/sabnzbd'
  - 'https://ghcr.io/onedr0p/exportarr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/sabnzbd'
