apiVersion: 'v2'
name: 'jellyfin'
description: 'A free software media system that puts you in control of managing and streaming your media'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/jellyfin'
keywords:
  - 'music'
  - 'tv'
  - 'television'
  - 'film'
  - 'movie'
  - 'ebooks'
  - 'manager'
  - 'stream'
  - 'media'
  - 'jellyfin'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.8.1
appVersion: 10.11.2
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/jellyfin/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.10.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/jellyfin/jellyfin'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/jellyfin'
