apiVersion: 'v2'
name: 'bazarr'
description: 'Companion application to Sonarr and Radarr to manage and download subtitles'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/bazarr'
keywords:
  - 'subtitles'
  - 'torrent'
  - 'bittorrent'
  - 'usenet'
  - 'manager'
  - 'radarr'
  - 'sonarr'
  - 'bazarr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.8.4
appVersion: 1.5.3
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/bazarr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.9.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/morpheus65535/Bazarr'
  - 'https://github.com/linuxserver/docker-bazarr'
  - 'https://ghcr.io/onedr0p/exportarr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/bazarr'
