apiVersion: 'v2'
name: 'transmission'
description: 'Simple and easy BitTorrent Client'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/transmission'
keywords:
  - 'transmission'
  - 'bittorrent'
  - 'torrent'
  - 'download'
  - 'usenet'
kubeVersion: ">=1.24.0-0"
type: 'application'
version: 0.5.2
appVersion: '4.0.6'
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/transmission/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.5.1
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/transmission/transmission'
  - 'https://github.com/linuxserver/docker-transmission'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/transmission'
