apiVersion: 'v2'
name: 'readarr'
description: 'Ebook and audiobook collection manager for Usenet and BitTorrent users'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/readarr'
keywords:
  - 'ebooks'
  - 'audiobooks'
  - 'torrent'
  - 'bittorrent'
  - 'usenet'
  - 'manager'
  - 'readarr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.5.4
appVersion: '0.3.32-develop'
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/readarr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.5.1
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/Readarr/Readar'
  - 'https://github.com/linuxserver/docker-readarr'
  - 'https://ghcr.io/onedr0p/exportarr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/readarr'
