apiVersion: 'v2'
name: 'flaresolverr'
description: 'Proxy server to bypass Cloudflare and DDoS-GUARD protection.'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/flaresolverr'
keywords:
  - 'flaresolverr'
  - 'proxy'
  - 'cloudflare'
  - 'bypass'
kubeVersion: ">=1.24.0-0"
type: 'application'
version: 0.8.1
appVersion: v3.4.1
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/flaresolverr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.9.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/FlareSolverr/FlareSolverr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/flaresolverr'
