apiVersion: 'v2'
name: 'homarr'
description: 'Sleek, modern dashboard that puts all of your apps and services at your fingertips'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/homarr'
keywords:
  - 'dashboard'
  - 'homarr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.17.0
appVersion: v1.37.0
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/homarr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.9.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/homarr-labs/homarr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/homarr'
