apiVersion: 'v2'
name: 'cleanuparr'
description: 'Companion application to Sonarr and Radarr to clean up failed and completed downloads'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/cleanuparr'
keywords:
  - 'torrent'
  - 'bittorrent'
  - 'radarr'
  - 'sonarr'
  - 'lidarr'
  - 'readarr'
  - 'whisparr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.3.0
appVersion: 2.3.0
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/cleanuparr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.9.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/Cleanuparr/Cleanuparr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/cleanuparr'
