apiVersion: 'v2'
name: 'jellyseerr'
description: 'Jellyseerr is a software application for managing requests for your media library.'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/jellyseerr'
keywords:
  - 'tv'
  - 'television'
  - 'film'
  - 'movie'
  - 'manager'
  - 'media'
  - 'jellyfin'
  - 'jellyseerr'
kubeversion: ">=1.24.0-0"
type: 'application'
version: 0.1.0
appVersion: '1.7.0'
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/jellyseerr/icon.png'
dependencies:
  - name: 'media-servarr-base'
    version: 0.4.0
    repository: "file://../.."
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/Fallenbagel/jellyseerr'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/jellyseerr'
